all:
	mkdir -p bin
	g++ cpp/moveTo0x44.cpp ../LIDARLite_RaspberryPi_Library/src/lidarlite_v3.cpp -I . -o bin/moveTo0x44.out
	g++ cpp/0x44_llv3.cpp ../LIDARLite_RaspberryPi_Library/src/lidarlite_v3.cpp -I . -o bin/0x44_llv3.out
	g++ cpp/0x62_llv3.cpp ../LIDARLite_RaspberryPi_Library/src/lidarlite_v3.cpp -I . -o bin/0x62_llv3.out
